server:
  port: 9080

#Postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url= jdbc:postgresql://localhost:5432/spring_test_20170823
#spring.datasource.username=postgres
#spring.datasource.password=postgres


#H2 Database
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sample-spring-boot-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: true

thymeleaf:
  cache: false

# For all example
error:
  message: ERROR

# For security example
security:
  id: foo
  pw: bar

# For math example
