server:
  port: 18080

#Postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url= jdbc:postgresql://localhost:5432/spring_test_20170823
#spring.datasource.username=postgres
#spring.datasource.password=postgres


#H2
spring:
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
  h2:
    console:
    enabled: true
  thymeleaf:
    cache: false
